### ISSUE TITLE
Do not override CMAKE_INSTALL_dirs

### ISSUE THREAD

**Issue by tripzero** [intel/hdcp#10]
Distributions are going to have different defaults for LIBDIR.  Overriding these defaults will result in libraries being installed in the wrong location on many distros.  These overrides should be removed, ie:

https://github.com/intel/hdcp/blob/intel-HDCP-18.3.0/CMakeLists.txt#L99

**Comment by miguelinux** [comment]
So, lets improve #9

**Comment by shiqiangyu** [comment]
Already merged #11
