### ISSUE TITLE
HDCPSetProtectionLevel does not set PortList.Ports[i].Status to correct value?

### ISSUE THREAD

**Issue by biskhand** [intel/hdcp#15]
After the HDCPGetStatus, we can see that `PortStatus` and `PortList.Ports[i].Status` are not the same. Is this expected? 
Shouldn't `PortList.Ports[i].Status` set like in https://github.com/intel/hdcp/blob/intel-HDCP-19.1.pre1/daemon/portmanager.cpp#L939 as well?

```
HDCPCreate(&handle, HDCP_Callback, NULL);
HDCPEnumerateDisplay(handle, &PortList);
...
HDCPSetProtectionLevel(handle, PortList.Ports[i].Id, HDCP_LEVEL1);
printf("biskhand:%s:%d Status=%u", __FUNCTION__, __LINE__, PortList.Ports[i].Status); // Status=1

PORT_STATUS PortStatus;
HDCPGetStatus(handle, PortList.Ports[i].Id, &PortStatus);

// Output --> PortStatus=3, PortList.Ports[i].Status=1
printf("biskhand:%s:%d [HDCP port %d] after HDCPSetProtectionLevel, PortStatus=%d, PortList.Ports[i].Status=%u",
    __FUNCTION__, __LINE__, PortList.Ports[i].Id, PortStatus, PortList.Ports[i].Status); 
...

```

**Comment by shiqiangyu** [comment]
PortList is defined in app, app should update it after getting portStatus.

Besides, you can find the HDCPGetStatus doesn't pass any PortList as parameter, hence there is no way to update it. Do you agree with it, @biskhand

**Comment by biskhand** [comment]
Yes, I agree with that. App should pass PortList variable instead of creating new variable for GetStatus.
Thanks for the info!
