### ISSUE TITLE
Supported Platforms

### ISSUE THREAD

**Issue by a1rwulf** [intel/hdcp#22]
> APL (Apollolake) for HDCP1.4
KBL (Kabylake) for HDCP1.4
GLK (Geminilake) for HDCP1.4 and HDCP2.2

Is this section still accurate?
I'm looking for a way to use HDCP2.2 for Kabylake and wanted to ask if this is already possible?

**Comment by bpscully** [comment]
Hi,
Yes that's accurate (HDCP 2.2 is not officially supported on KBL). 
It's not explicitly disabled and HDCP 2.2 will authenticate, but there is a known issue:

>>KBL: Blank screen after enabling HDCP 2.2. This is a known issue on KBL hardware.

**Comment by a1rwulf** [comment]
Thanks for the fast response.
Is there any work in progress that will fix this issue?
Or is the main focus on other developments?

**Comment by shiqiangyu** [comment]
@a1rwulf, the i915 display team has software workaround for the KBL hardware issue, and the fix has been upstreamed to [https://cgit.freedesktop.org/drm-tip/](https://cgit.freedesktop.org/drm-tip/kernel) and [https://github.com/freedesktop/drm-tip](https://github.com/freedesktop/drm-tip) Linux kernel repository.

**Comment by a1rwulf** [comment]
@shiqiangyu good news :+1: 
Thanks for the information, I think this issue is done then.
