### ISSUE TITLE
Calling init() on dlopen libwl_base.so fails

### ISSUE THREAD

**Issue by kevineddrs** [intel/hdcp#26]
In daemon/display_window_util_wl.cpp line 77:

ret = gwl->init();

This returns 0, thus going to the failure portion of the code.  Unfortunately, 0 doesn't tell us why it is failing.  There doesn't seem to be any source code or documentation associated with the libwl_base.so library either.

**Comment by shiqiangyu** [comment]
Thanks for the comments. errno is set corresponding when gwl->init() failed, I have added the error print in cacc352 commit. libwl_base.so is merged from a PR, will ask the submitter to clarify its usage.
