### ISSUE TITLE
the cmake file is broken and installs the library in a non-standard location

### ISSUE THREAD

**Issue by fenrus75** [intel/hdcp#4]
cmake supports installing .so files in their proper place.

sadly this project does not use it and as a result the shared lib goes into /usr/lib/x86_64-linux-gnu/libhdcpsdk.so instead of hte proper location.

in addition, clearly something else is broken since the soname setup of shared libraries is not being used...

**Comment by chivakker** [comment]
Installing prefix should be honored by the installing Makefile.  User may want to install this library in any directory.

**Comment by shiqiangyu** [comment]
Thanks for the comments.
We are working in progress to provide more cmake options to set preference location for installed libraries.

**Comment by shiqiangyu** [comment]
In the latest commit, we updated the installation location to /usr/local/<bin or lib>. Users can also specify it via setting the CMAKE_INSTALL_PREFIX variable.
