### ISSUE TITLE
the cmake file is broken and install systemd unit files to an invalid location

### ISSUE THREAD

**Issue by fenrus75** [intel/hdcp#6]
systemd unit files need to be installed to a proper location, not /etc

cmake can do this properly (by checking systemd where to install these) but this projects cmake files are not doing that.

**Comment by shiqiangyu** [comment]
Thanks for the comments.
Currently cmake file supports auto start on Ubuntu platform by installing hdcpd.service at /etc/systemd/system folder. 

If running on platforms without /etc folder. Please skip auto start by commenting out these 2 lines in hdcp/CMakeLists.txt
install (FILES ${CMAKE_SOURCE_DIR}/config/hdcpd.service DESTINATION ${CMAKE_SYSTEMD_INSTALL_DIR} COMPONENT cp)
SET(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA ${CMAKE_SOURCE_DIR}/config/postinst)

And we are working in process to support more platforms.

**Comment by ahkok** [comment]
Packages should by default install service unit files under /usr/lib/systemd/system by default, not /etc.

A good way to do this is something like this:

https://github.com/ximion/limba/blob/master/data/cmake/systemdservice.cmake

Note: it properly uses pkg-config to *ask* systemd where it's system unit dir actually is.

**Comment by shiqiangyu** [comment]
We used pkg-config for checking the systemd location, and already pushed the updated cmake file, thanks.
